<?php

/*** Configure your database settings in the next cpl of lines ****************/
$server_name = "B3 enabled server";
$db_host = "localhost";
$db_name = "";
$db_username = "";
$db_password = "";

/*** DO NOT EDIT BELOW THIS LINE!! ********************************************/
error_reporting( E_ERROR ^ E_WARNING );
$db = mysql_pconnect($db_host, $db_username, $db_password) or die(mysql_error());
mysql_select_db($db_name, $db);
// permbans:
$query_rs_activebans = sprintf("SELECT penalties.id, penalties.type, penalties.time_add, penalties.time_expire, penalties.reason, penalties.inactive, penalties.duration, penalties.admin_id, target.id as target_id, target.name as target_name, target.ip as target_ip, target.guid FROM penalties, clients as target WHERE penalties.type = 'Ban' AND inactive = 0 AND penalties.client_id = target.id AND ( penalties.time_expire = -1) ORDER BY penalties.id DESC");
// tempbans
//$query_rs_activebans = sprintf("SELECT penalties.id, penalties.type, penalties.time_add, penalties.time_expire, penalties.reason, penalties.inactive, penalties.duration, penalties.admin_id, target.id AS target_id, target.name AS target_name, target.ip AS target_ip, target.guid FROM penalties INNER JOIN clients target ON penalties.client_id = target.id WHERE penalties.type = 'TempBan' AND penalties.inactive = 0 AND penalties.time_expire >= UNIX_TIMESTAMP(NOW()) + 432000 ORDER BY  penalties.id DESC");

$rs_activebans = mysql_query($query_rs_activebans, $db) or die(mysql_error());
$num_rows = mysql_num_rows($rs_activebans);

header("Content-type: text/plain");
header("Cache-Control: no-store, no-cache");
echo "\n";
echo "//------------------------------------------------------\n";
echo "//            " . $server_name . " BAN LIST\n";
echo "//------------------------------------------------------\n";
echo "// Count :  " . $num_rows . " permanent bans\n";
echo "// Generated :   " . date(DATE_ATOM, time()) . "\n";
echo "//------------------------------------------------------\n";
echo "//\n";
echo "// This banlist was generated by BigBrotherBot. \n";
echo "//\n";
echo "// You can use the URL to load this banlist in the banlist\n";
echo "// plugin for BigBrotherBot.\n";
echo "//\n";
echo "// More information about usage on www.bigbrotherbot.net\n";
echo "//    http://forum.bigbrotherbot.net/plugins-by-courgette/banlist-plugin/\n";
echo "// Download the plugin here: \n";
echo "//    http://forum.bigbrotherbot.net/downloads/?sa=view;down=6\n";
echo "//\n";
echo "//------------------------------------------------------\n";
echo "\n";
echo "//IP  <Playername> banned on <Date & Time>, reason: <Reason>\n";
echo "\n";
while ($row = mysql_fetch_assoc($rs_activebans)) {
    $text .= $ban['target_ip'] . '  ';
    $text .= $row['target_name'];
    $text .= ' banned on  ' . date('m/d/Y (H:i)',$row['time_add']);
    $text .= ', reason : ' . $row['reason'];
    echo $text . "\n";
}
mysql_free_result($rs_activebans);

?>